src/Entity/Pokemon.php
<?php

namespace App\Entity;

use App\Repository\PokemonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PokemonRepository::class)]
class Pokemon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $base_experience = null;

    #[ORM\Column(length: 255)]
    private ?string $sprite = null;

    #[ORM\ManyToMany(targetEntity: Ability::class, mappedBy: 'pokemon')]
    private Collection $abilities;

    #[ORM\ManyToMany(targetEntity: Type::class, mappedBy: 'pokemon')]
    private Collection $types;

    #[ORM\ManyToOne(targetEntity:Team::class, cascade: ['persist'], inversedBy: 'pokemon')]
    private ?Team $team = null;

    public function __construct()
    {
        $this->abilities = new ArrayCollection();
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBaseExperience(): ?int
    {
        return $this->base_experience;
    }

    public function setBaseExperience(int $base_experience): self
    {
        $this->base_experience = $base_experience;

        return $this;
    }

    public function getSprite(): ?string
    {
        return $this->sprite;
    }

    public function setSprite(string $sprite): self
    {
        $this->sprite = $sprite;

        return $this;
    }

    /**
     * @return Collection<int, Ability>
     */
    public function getAbilities(): Collection
    {
        return $this->abilities;
    }

    public function addAbility(Ability $ability): self
    {
        if (!$this->abilities->contains($ability)) {
            $this->abilities->add($ability);
            $ability->addPokemon($this);
        }

        return $this;
    }

    public function removeAbility(Ability $ability): self
    {
        if ($this->abilities->removeElement($ability)) {
            $ability->removePokemon($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Type>
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types->add($type);
            $type->addPokemon($this);
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        if ($this->types->removeElement($type)) {
            $type->removePokemon($this);
        }

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    public array $typeList;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTime $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'team', targetEntity: Pokemon::class)]
    private Collection $pokemon;

    public function __construct()
    {
        $this->pokemon = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Pokemon>
     */
    public function getPokemon(): Collection
    {
        return $this->pokemon;
    }

    public function addPokemon(Pokemon $pokemon): self
    {
        if (!$this->pokemon->contains($pokemon)) {
            $this->pokemon->add($pokemon);
            $pokemon->setTeam($this);
        }

        return $this;
    }

    public function removePokemon(Pokemon $pokemon): self
    {
        if ($this->pokemon->removeElement($pokemon)) {
            // set the owning side to null (unless already changed)
            if ($pokemon->getTeam() === $this) {
                $pokemon->setTeam(null);
            }
        }

        return $this;
    }

    public function getAllPokemonType(): array
    {
        $this->typeList = array();
        foreach ($this->pokemon as $pokemon) {
            foreach ($pokemon->getTypes() as $type) {
                if (!in_array($type->getName(), $this->typeList)) {
                    $this->typeList[$type->getId()] = $type->getName();
                }
            }
        }
        asort($this->typeList);
        return $this->typeList;
    }
}

src/Form/TeamType.php
<?php

namespace App\Form;

use App\Entity\Team;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class)
            ->add('ajaxString',HiddenType::class, [
                'mapped' => false,
                'attr' => ['class' => 'hidden-field', 'value' => '']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Team::class,
        ]);
    }
}

src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Form\TeamType;
use App\Repository\AbilityRepository;
use App\Repository\TeamRepository;
use App\Repository\TypeRepository;
use App\Service\PokemonService;
use App\Service\TeamService;
use App\Service\TypeService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Cache\InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;

class TeamController extends AbstractController
{
    #[Route('/team', name: 'homepage_team')]
    public function index(Request $request): Response
    {
        return $this->redirectToRoute('app_default');
    }

    /**
     * @throws RedirectionExceptionInterface
     * @throws ClientExceptionInterface
     * @throws ServerExceptionInterface|InvalidArgumentException
     */
    #[Route('/team/create', name: 'create_team')]
    public function createTeam(
        Request $request,
        EntityManagerInterface $entityManager,
        TypeRepository $typeRepository,
        AbilityRepository $abilityRepository
    ): Response {
        $team = new Team();
        $team->setName('');
        $team->setCreatedAt(new \DateTime());
        $team->setUpdatedAt(new \DateTimeImmutable());

        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $team = $form->getData();
            $pokemonList = $form->get('ajaxString')->getData();
            $pokemonService = new PokemonService(HttpClient::create(), $entityManager, $typeRepository,
                $abilityRepository);
            $pokemonService->addPokemonList($team, $pokemonList);
            $this->addFlash(
                'success',
                'Your changes were saved!'
            );
            return $this->redirectToRoute('list_teams');
        }
        return $this->render('team/create.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @throws InvalidArgumentException
     */
    #[Route('/team/list', name: 'list_teams')]
    public function listTeams(TeamService $teamService, TypeService $typeService): Response
    {
        $teams = $teamService->getTeamsCache();
        $types = $typeService->getTypeCached();

        return $this->render('team/list.html.twig', [
            'teams' => $teams,
            'types' => $types
        ]);
    }

    #[Route('/team/{teamId}/edit', name: 'edit_team')]
    public function editTeam(
        int $teamId,
        Request $request,
        EntityManagerInterface $entityManager,
        TeamRepository $teamRepository
    ): Response {
        $team = $teamRepository->find($teamId);
        $form = $this->createForm(TeamType::class, $team);
        $form->remove('created_at');
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $team = $form->getData();
            $entityManager->persist($team);
            $entityManager->flush();
            return $this->redirectToRoute('list_teams');
        }
        return $this->render('team/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/team/{teamId}/delete', name: 'delete_team')]
    public function deleteTeam(
        int $teamId,
        Request $request,
        EntityManagerInterface $entityManager,
        TeamRepository $teamRepository
    ): Response {
        $team = $teamRepository->find($teamId);
        if ($team == null)
            return $this->redirectToRoute('list_teams');

        $pokemons = $team->getPokemon();
        foreach ( $pokemons as $pokemon ){
            if($pokemon->getTeam() == $team){
                $pokemon->setTeam(null);
                $team->removePokemon($pokemon);
            }
        }
        $teamRepository->remove($team, true);
        $entityManager->persist($team);
        $entityManager->flush();

        return $this->redirectToRoute('list_teams');
    }

}

templates/team/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Pokémon team!{% endblock %}

{% block body %}
    <h1 class="display-5 fw-bold">Create team!</h1>
    <p class="col-md-8 fs-4">A real Poke master wins with any Pokémon, let them choose at random.<br>
        Pressing the "Gotta Catch 'Em All" button, when you are satisfied save your team!</p>
    <p></p>
    {{ form_start(form, {'attr': {'id': 'formTeam', 'onsubmit':'return validateForm();'}}) }}
    {{ form_rest(form) }}
    <div class="container mx-auto mt-4" id="PokemonTeam">
        <div class="row">
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card free" style="width: 15rem;">
                    <img src="/poke.gif"
                         class="card-img-top" alt="Poke ball">
                    <div class="card-body">
                        <h5 class="card-title">Pokemon</h5>
                        <h6 class="card-subtitle mb-2 text-muted">EXP</h6>
                        <p class="card-text">Abilities:</p>
                        <p class="card-text">Types:</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-primary" onclick="addPokemonToTeam()">Gotta Catch 'Em All</a>
    <button class="btn btn-success" name="Insert" type="submit">Save team</button>
    <a href="/team/create" class="btn btn-secondary" style="float: right">Reset</a>
    <a href="/team" class="btn btn-secondary" style="float: right; margin-right: 2px">Homepage</a>
    {{ form_end(form) }}
{% endblock %}

{% block footer_js %}
     <script src="{{ asset('js/create.js') }}"></script>
{% endblock %}

templates/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pokémon team{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_rest(form) }}
    <button type="submit" class="btn btn-primary" name="Edit">Edit team</button>
    <a href="/team" class="btn btn-secondary" style="float: right; margin-right: 2px">Homepage</a>
    {{ form_end(form) }}
{% endblock %}

templates/team/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of Pokémon{% endblock %}

{% block body %}
    <h1 class="display-5 fw-bold">List of created team</h1>
    <p class="col-md-8 fs-4">Here are all your Pokémon teams you created, <br>
        on the right you will find the action buttons to edit or delete the team</p>
    <label for="selectPokemonType">Filter by Pokémon type:</label>
    <select class="selectpicker" multiple data-live-search="true" id="selectPokemonType" data-style="btn-info">
        {% for type in types %}
            <option value="{{ type.id }}">{{ type.name }}</option>
        {% endfor %}
    </select>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Sprite</th>
            <th scope="col">Sum Exp</th>
            <th scope="col">Types</th>
            <th scope="col">Creation date</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for team in teams %}
            <tr id="team_id_{{ team.id }}">
                <th scope="row">{{ team.id }}</th>
                <td> {{ team.name }}</td>
                <td>{% for pokemon in  team.pokemon %}
                        <img class="img-thumbnail col-sm-3" src="{{ pokemon.sprite }}" alt="Pokemon sprite"/>
                    {% endfor %}
                </td>
                <td> {% set sum = 0 %}
                    {% for pokemon in  team.pokemon %}
                        {% set sum = sum + pokemon.baseExperience %}
                    {% endfor %}
                    {{ sum }}</td>
                <td>
                    <ul>
                        {% for typeId, typeName in team.typeList %}
                            <li data-type="{{ typeId }}"><img
                                        src="https://veekun.com/dex/media/types/en/{{ typeName }}.png" alt="type"/></li>
                        {% endfor %}
                    </ul>
                </td>
                <td> {{ team.createdAt | date('d-m-Y') }}</td>
                <td><a class="btn btn-primary" href="/team/{{ team.id }}/edit" role="button">Edit</a></td>
                <td><a class="btn btn-primary" href="/team/{{ team.id }}/delete" role="button">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="/team/create" class="btn btn-secondary" style="float: right">Create new team</a>
    <a href="/team" class="btn btn-secondary" style="float: right; margin-right: 2px">Homepage</a>
{% endblock %}
{% block footer_js %}
    <script src="{{ asset('js/list.js') }}"></script>
{% endblock %}